---
# https://github.com/nalgeon/podsearch-py/tree/main/.github/workflows
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    env:
      USING_COVERAGE: '3.10'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions pytest black coverage requests pytest-asyncio

      - name: Run tox
        run: |
          make tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: contains(env.USING_COVERAGE, matrix.python-version)
        with:
          fail_ci_if_error: true
